Add naive 3-coloring algorithm
schizofrenicy/3-coloring-algorithm pull request #1
Opened 2023-05-23 23:39 UTC by Sosssen

* Install QuikGraph NuGet Package
* Add function to check if graph is properly 3-colored

2023-06-04 16:14 UTC, H3w9VH3F4L4Tq5MbsfRi requested changes
odnieś się i pogadamy

2023-06-04 16:14 UTC, H3w9VH3F4L4Tq5MbsfRi commented on 3-coloring-algorithm/NaiveAlgorithm.cs
> +            if (Naive3ColoringRecursive(g, 0))
w `Naive3ColoringRecursive` daj parametrowi `vertex` wartość domyślną 0
będzie b. elegancko

2023-06-04 16:14 UTC, H3w9VH3F4L4Tq5MbsfRi commented on 3-coloring-algorithm/NaiveAlgorithm.cs
> +            }
niepotrzebne klamry w tym if'ie

2023-06-04 16:14 UTC, H3w9VH3F4L4Tq5MbsfRi commented on 3-coloring-algorithm/ProperColoringChecker.cs
> +                foreach (var neighbor in neighbors)
nie używaj `neighbor` i `neighborS`, bo przy pobieżnym czytaniu nie widać rożnicy
zalecam `n` i `neighbors`

2023-06-04 16:14 UTC, H3w9VH3F4L4Tq5MbsfRi commented on 3-coloring-algorithm/ProperColoringChecker.cs
> +                }
niepotrzebne klamry

2023-06-04 16:14 UTC, H3w9VH3F4L4Tq5MbsfRi commented on 3-coloring-algorithm/Program.cs
> +            Console.WriteLine(result);
daj tutaj jakiś b mądry komunikat niż `true` / `false`

2023-06-04 16:14 UTC, H3w9VH3F4L4Tq5MbsfRi commented on 3-coloring-algorithm/Program.cs
> +            //g.AddEdge(new SUndirectedEdge<int>(1, 3));
to do wywalenia jak będzie algorytm do generacji

2023-06-05 13:10 UTC, Sosssen commented on 3-coloring-algorithm/Program.cs
> +            UndirectedGraph<int, SUndirectedEdge<int>> g = new UndirectedGraph<int, SUndirectedEdge<int>>();
done

2023-06-05 13:11 UTC, Sosssen commented on 3-coloring-algorithm/Program.cs
> +            var result = NaiveAlgorithm.Naive3Coloring(g, out int[] colors);
done

2023-06-05 13:12 UTC, Sosssen commented on 3-coloring-algorithm/NaiveAlgorithm.cs
> +            if (Naive3ColoringRecursive(g, 0))
done

2023-06-05 13:15 UTC, Sosssen commented on 3-coloring-algorithm/NaiveAlgorithm.cs
> +            }
potrzebne
https://armannotes.com/2020/11/23/why-you-should-always-use-curly-braces-for-single-statement-blocks-in-csharp/

2023-06-05 13:16 UTC, Sosssen commented on 3-coloring-algorithm/ProperColoringChecker.cs
> +                foreach (var neighbor in neighbors)
done

2023-06-05 13:16 UTC, Sosssen commented on 3-coloring-algorithm/ProperColoringChecker.cs
> +                }
potrzebne,
https://armannotes.com/2020/11/23/why-you-should-always-use-curly-braces-for-single-statement-blocks-in-csharp/

2023-06-05 13:17 UTC, Sosssen commented on 3-coloring-algorithm/Program.cs
> +            //g.AddEdge(new SUndirectedEdge<int>(1, 3));
funkcja main będzie się zmieniać na przestrzeni całego projektu w zależności od aktualnych potrzeb do testowania
docelowo będzie tylko pętla która generuje graf, wykonuje algorytm i wypisuje czas i tak w kółko, na razie bym nie przejmował się tym co jest w mainie, ma to tylko ułatwić testowanie

2023-06-05 13:18 UTC, Sosssen commented on 3-coloring-algorithm/Program.cs
> +            Console.WriteLine(result);
jak niżej

2023-06-05 16:28 UTC, H3w9VH3F4L4Tq5MbsfRi approved these changes

2023-06-05 16:31 UTC, merged